export const layoutConfig = [
  { display: "C", value: "C", id: "clear", className: "clear-button" },
  { display: "(", value: "(" },
  { display: ")", value: ")" },
  { display: "/", value: "/", id: "divide" },
  { display: "7", value: "7", id: "seven" },
  { display: "8", value: "8", id: "eight" },
  { display: "9", value: "9", id: "nine" },
  { display: "*", value: "*", id: "multiply" },
  { display: "4", value: "4", id: "four" },
  { display: "5", value: "5", id: "five" },
  { display: "6", value: "6", id: "six" },
  { display: "-", value: "-", id: "subtract" },
  { display: "1", value: "1", id: "one" },
  { display: "2", value: "2", id: "two" },
  { display: "3", value: "3", id: "three" },
  { display: "+", value: "+", id: "add" },
  { display: "0", value: "0", id: "zero", className: "zero-button" },
  { display: ".", value: ".", id: "decimal" },
  { display: "=", value: "=", id: "equals", className: "equals-button" },
]